enum ProductActions {
    SET_CURRENT_PRODUCTS = "SET_CURRENT_PRODUCTS",
    SET_ALL_PRODUCT = "SET_ALL_PRODUCT",
    SET_CURRENT_SORT = "SET_CURRENT_SORT",
    SET_DEFAULT_PRODUCT = "SET_DEFAULT_PRODUCT"
}

export default ProductActions;
