enum ProductActions {
    SET_CURRENT_PRODUCTS = "SET_CURRENT_PRODUCTS",
    SET_ALL_PRODUCT = "SET_ALL_PRODUCT",
    SET_CURRENT_SORT = "SET_CURRENT_SORT",
    SET_DEFAULT_PRODUCT = "SET_DEFAULT_PRODUCT",
    SET_LOADING = "SET_LOADING",
    SET_HISTORY_ACTIVE = "SET_HISTORY_ACTIVE",
    SET_HISTORY = "SET_HISTORY"
}

export default ProductActions;
